version: '2'
services:
  front:
    build:
      context: .
      dockerfile: "Dockerfile.front.dev"
    command: "yarn run dev"
    volumes:
      - ".:/app"
    volumes_from:
      - data
    ports:
      - "3333:3333"
    tty: true
    stdin_open: true
  rails:
    build:
      context: .
      dockerfile: "Dockerfile.rails.dev"
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:10.3"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes_from:
      - data
    ports:
      - "5432:5432"
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/postgresql/data"
      - "bundle:/usr/local/bundle"
      - "node_modules:/app/node_modules"

volumes:
  db:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
